# Generated by Django 5.2.3 on 2025-06-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_images_product_image1_product_image2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_description',
            new_name='description_full',
        ),
        migrations.AddField(
            model_name='product',
            name='description_short',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
